<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="11" time="0.640" timestamp="2024-11-03T12:25:43.605622-05:00" hostname="DESKTOP-69FJA4Q"><testcase classname="test_api" name="test_getBooks_gToken_whenNoApiAccessToken_shouldReturn403" time="0.009" /><testcase classname="test_api" name="test_getBooks_gToken_whenValidApiAccessToken_shouldReturn200" time="0.035" /><testcase classname="test_api" name="test_getBooks_searchById_whenValidId_shouldReturnBook" time="0.030" /><testcase classname="test_api" name="test_getBooks_searchById_whenInvalidId_shouldReturn404" time="0.030"><failure message="assert 404 == 999&#10; +  where 404 = &lt;Response [404]&gt;.status_code">context = {'book_ids': []}

    def test_getBooks_searchById_whenInvalidId_shouldReturn404(context):
        # Given G-Token is provided
        headers = { 'g-token': ConfigProvider.get_g_token() }
    
        # When a book is requested by an invalid ID
        url = ConfigProvider.get_host() + "/books/9999999999999999999999999999"
        response = requests.request("GET", url, headers=headers, data="")
    
        # Then 404 is returned
&gt;       assert response.status_code == 999
E       assert 404 == 999
E        +  where 404 = &lt;Response [404]&gt;.status_code

test_api.py:55: AssertionError</failure></testcase><testcase classname="test_api" name="test_getBooks_searchByTitle_whenValidTitle_shouldReturnBook" time="0.035" /><testcase classname="test_api" name="test_getBooks_searchByTitle_whenInvalidTitle_shouldReturnNoBooks" time="0.031" /><testcase classname="test_api" name="test_getBooks_searchByAuthor_whenValidAuthor_shouldReturnBook" time="0.031" /><testcase classname="test_api" name="test_getBooks_whenInvalidAuthor_shouldReturnNoBooks" time="0.031" /><testcase classname="test_api" name="test_postBooks_addBook_whenValidRequest_shouldSuccessfullyAddBook" time="0.062" /><testcase classname="test_api" name="test_deleteBooks_deleteBook_whenValidBasicAuth_shouldDeleteBook" time="0.120"><failure message="assert 404 == 999&#10; +  where 404 = &lt;Response [404]&gt;.status_code">context = {'book_ids': [48]}

    def test_deleteBooks_deleteBook_whenValidBasicAuth_shouldDeleteBook(context):
        # Given a book has been added
        unique = str(time.time()*1000000).replace('.','')
        title = "Automation Book " + unique
        author = "Automation Author " + unique
        isbn = "1234" + unique
        releaseDate = "2019-02-01"
        response = requests.request("POST", ConfigProvider.get_host() + "/books", headers={'g-token': 'ROM831ESV','Content-Type': 'application/json','Authorization': 'Basic Og=='}, data=json.dumps({"title": title,"author": author,"isbn": isbn,"releaseDate": releaseDate}))
        book_id = response.json()["id"]
        context["book_ids"].append(response.json()["id"])
    
        # And Basic Auth credentials are provided (the user has authorization to delete)
        auth = HTTPBasicAuth(ConfigProvider.get_username(), ConfigProvider.get_password())
    
        # When the book is deleted
        url = ConfigProvider.get_host() + "/books/" + str(book_id)
        headers = {
            'g-token': 'ROM831ESV',
            'Content-Type': 'application/json'
            }
        response = requests.request("DELETE", url, headers=headers, auth=auth)
    
        # Then 204 is returned
        assert response.status_code == 204
    
        # And the book is not found when requested
        url = ConfigProvider.get_host() + "/books/" + str(book_id)
        headers = { 'g-token': ConfigProvider.get_g_token() }
        response = requests.request("GET", url, headers=headers, data="")
&gt;       assert response.status_code == 999
E       assert 404 == 999
E        +  where 404 = &lt;Response [404]&gt;.status_code

test_api.py:179: AssertionError</failure></testcase><testcase classname="test_api" name="test_deleteBooks_deleteBook_whenInvalidBasicAuth_shouldNotDeleteBook" time="0.092" /></testsuite></testsuites>